networks:
  default:
    name: opentdf_platform

services:
  opentdfdb:
    image: postgres:15-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: opentdf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  opentdf:
    image: custom-opentdf:latest
    restart: always
    volumes:
      - "./keys:/keys"  # Mount your keys directory
      - "./opentdf.yaml:/home/nonroot/.opentdf/opentdf.yaml"  # Mount opentdf.yaml
      - "./keys/local-dsp.virtru.com.pem:/usr/local/share/ca-certificates/ca.crt"  # Mount the cert file
    networks:
      - default
    ports:
      - "8080:8080"  # Expose the service on port 8080
    environment:
      SSL_CERT_DIR: "/usr/local/share/ca-certificates"  # Ensure the cert dir is set
    entrypoint: ["/usr/bin/opentdf","start"]
    extra_hosts:
      - "local-dsp.virtru.com:192.168.1.195"  # Add custom host entries
